# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: 12.x
             
      # Install deps
      - name: Install dependencies
        run: yarn
      # Build the app
      - name: Run Build
        run: yarn build
      # Copy dist folder to Digital Ocean and replace with the current code
      - name: Copy dist folder to DO
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{secrets.SSH_KEY}}
         port: ${{ secrets.SSH_PORT }}
         source: "., !node_modules"
         target: "~/app/first-node-repo"

    # Execute yarn in Digital Ocean
      - name: Install all deps on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: |
             cd ~/app/first-node-repo
             yarn

    # Execute Migrations
      
      - name: Run migrations on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: |
             cd ~/app/first-node-repo
             ./node_modules/.bin/typeorm migration:run
      
    # Restart Server
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: pm2 restart gobarber-api
