# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: 12.x
      # Install deps
      - name: Install dependencies
        run: yarn
      # Build the app
      - name: Run Build
        run: yarn build
      
      - name: Copy dist folder to DO
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{secrets.SSH_KEY}}
         port: ${{ secrets.SSH_PORT }}
         source: "dist"
         target: "test"

    # Copy dist folder to Digital Ocean
    # Replace the current code on dist folder for the new code
    # Execute yarn in Digital Ocean
    # Execute Migrations
    # Restart Server
